#Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d8uk6n0g4nts73fu1tn0-a.singapore-postgres.render.com/moneymanager_mhsb
spring.datasource.username=moneymanager_mhsb_user
spring.datasource.password=DCEr666bERE5RQnrXGBg6pec5pt7gnPZ